# crf模型使用基础 

In [138]:
!pip show torchcrf

Name: TorchCRF
Version: 1.1.0
Summary: An Implementation of Conditional Random Fields in pytorch
Home-page: https://github.com/s14t284/TorchCRF
Author: Ryuya Ikeda
Author-email: rikeda71@gmail.com
License: MIT
Location: c:\python37\lib\site-packages
Requires: torch, numpy
Required-by: 


In [55]:
import torch
# 安装 torchcrf   pip install pytorch-crf -i https://pypi.tuna.tsinghua.edu.cn/simple/
# pip list 显示的时候是 TorchCRF 然而导入的时候是用 import torchcrf 或者 from torchcrf import CRF
from torchcrf import CRF

num_tags = 5  # 实体命名识别 每个汉字可以预测多少中类型 
# model = CRF(num_tags,batch_first=True)
model = CRF(num_tags)
seq_length = 3  # 句子长度（一个句子有三个单词）
batch_size = 1  # batch大小 一共输入几个句子 在这里是一个 句子
# hidden= torch.randn(batch_size,seq_length,num_tags) # 输入的是 batch：几个句子 ，seq_length：每个句子的长度 
hidden= torch.rand(batch_size,seq_length,num_tags) # 输入的是 batch：几个句子 ，seq_length：每个句子的长度 
print(hidden.shape)# torch.Size([1, 3, 5])
# 表示：一个句子 句子长度是3 每个单词的维度是 5 ，为什么是5呢？因为是为每个单词打标签，一共有五个标签 所以
print(hidden)

mask = torch.tensor([[1,1,0]], dtype=torch.uint8) # mask的意思是 有的汉字的向量 不进行标签的预测  
# mask的形状是:[batch，seq_length]
# 这句话由于torchcrf版本不同 进而 函数设置不同 batch_first=True 假设没有这句话  那么输入模型的第一个句子序列的 mask都是true，假设有这句话 就没事 ，mask是正常的
# mask的作用是：因为是中文的句子 那么每句话都要padding 一定的长度 所以 告诉模型那些是padding的 

tags = torch.tensor([[0,2,3]], dtype=torch.long)  #(batch_size, seq_length)

loss=model(hidden,tags,mask)  # 计算对数似然（用于向前） loss 
print(loss)
a=model.viterbi_decode(hidden,mask)  # 或者用 model.decode(hidden,mask)
print(a)

torch.Size([1, 3, 5])
tensor([[[0.5988, 0.6661, 0.7610, 0.2041, 0.1719],
         [0.9909, 0.3134, 0.3760, 0.2873, 0.7383],
         [0.9339, 0.2130, 0.5103, 0.0713, 0.7942]]])
tensor([-3.4701], grad_fn=<SubBackward0>)
[[2, 0]]


In [27]:
# pip install pytorch-crf -i https://pypi.tuna.tsinghua.edu.cn/simple/
import torch
from torchcrf import CRF
 
num_tags = 5  # number of tags is 5
model = CRF(num_tags)
 
seq_length = 3  # maximum sequence length in a batch
batch_size = 2  # number of samples in the batch
 
hidden= torch.randn(batch_size,seq_length,num_tags)
print(hidden)
 
mask = torch.tensor([[1, 1,1], [1, 1,0]], dtype=torch.uint8)
 
tags = torch.tensor([[0,2,3], [1,4,1]], dtype=torch.long)  #(batch_size, seq_length)
 
model(hidden,tags,mask)  # 计算对数似然（用于向前）
 
model.viterbi_decode(hidden,mask) # 解码（预测序列标签）
# crf.viterbi_decode(hidden,mask) # 解码（预测序列标签）

tensor([[[ 0.4690, -1.0011,  1.9207, -1.3772,  1.4006],
         [ 0.9187,  0.3772,  1.9090,  2.1411,  1.2858],
         [ 0.0591, -1.3176, -2.2238,  0.6061,  0.4469]],

        [[-0.7444,  1.1173,  0.1946, -0.2796, -0.0560],
         [ 0.4838,  2.4101, -0.5735,  0.2289,  0.6405],
         [-0.8739, -0.4133,  2.6319, -1.0350, -2.5549]]])


[[2, 3, 3], [1, 1]]

In [9]:
! pip list

Package                         Version
------------------------------- -----------
absl-py                         0.11.0
aiohttp                         3.7.4.post0
altgraph                        0.17
antlr4-python3-runtime          4.8
anyio                           2.0.2
argon2-cffi                     20.1.0
ase                             3.20.1
astor                           0.8.1
astunparse                      1.6.3
async-generator                 1.10
async-timeout                   3.0.1
attrs                           20.3.0
axial-positional-embedding      0.2.1
Babel                           2.9.0
backcall                        0.2.0
beautifulsoup4                  4.9.3
bert4keras                      0.10.7
biogeme                         3.2.6
bleach                          3.2.1
blis                            0.7.4
bs4                             0.0.1
cached-property                 1.5.2
cachetools                      4.2.1
catalogue                       2.0

In [20]:
import torch
# from TorchCRF import CRF 
from torchcrf import CRF

batch_size=2
sequence_size=3
num_labels=5

mask=torch.FloatTensor([[1,1,1],[1,1,0]])               #(batch_size. sequence_size)

labels=torch.tensor([[0,2,3],[1,4,1]],dtype=torch.long) #(batch_size, sequence_size)
print(labels)

hidden=torch.randn((batch_size,sequence_size,num_labels),requires_grad=True)

crf=CRF(num_labels)


tensor([[0, 2, 3],
        [1, 4, 1]])


In [25]:
crf.viterbi_decode(hidden,mask) # 解码（预测序列标签）

[[2]]